-- Create tables
CREATE TABLE USER (
	ID INT NOT NULL,
	FName VARCHAR(20),
	LName VARCHAR(20),
	Username VARCHAR(30),
	Password VARCHAR(30),
	Balance DECIMAL(7, 2),
	PRIMARY KEY (ID)
);

CREATE TABLE COMPANY (
	ID INT NOT NULL,
	Name VARCHAR(30),
	PRIMARY KEY (ID)
);

CREATE TABLE GUITAR (
	ID INT NOT NULL,
	Name VARCHAR(150),
	Price DECIMAL(7, 2),
	Company_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE PURCHASE (
	ID INT NOT NULL,
	User_ID INT,
	User_balance DECIMAL(7, 2),
	Item_ID INT,
	Buy_date DATETIME,
	PRIMARY KEY (ID),
	FOREIGN KEY (User_ID) REFERENCES USER(ID),
	FOREIGN KEY (User_balance) REFERENCES USER(Balance),
	FOREIGN KEY (Item_ID) REFERENCES ITEM(ID)
);