-- Create tables
CREATE TABLE USER (
	ID INT NOT NULL,
	FName VARCHAR(20),
	LName VARCHAR(20),
	Username VARCHAR(30),
	Password VARCHAR(30),
	Balance DECIMAL(7, 2),
	PRIMARY KEY (ID)
);

CREATE TABLE COMPANY (
	ID INT NOT NULL,
	Name VARCHAR(30),
	PRIMARY KEY (ID)
);

CREATE TABLE GUITAR (
	ID INT NOT NULL,
	Name VARCHAR(150),
	Picture VARCHAR(255),
	Description VARCHAR(1023),
	Price DECIMAL(7, 2),
	Company_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID)
);

CREATE TABLE CART (
    ID INT NOT NULL,
    User_ID INT,
    Date_made DATETIME,
    PRIMARY KEY (ID),
    FOREIGN KEY (User_ID) REFERENCES USER(ID)
);

CREATE TABLE CART_ITEM (
    ID INT NOT NULL,
    Item_ID INT,
    Quantity INT,
    Date_made DATETIME,
    Cart_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (Item_ID) REFERENCES GUITAR(ID),
    FOREIGN KEY (Cart_ID) REFERENCES CART(ID)
)