-- Create tables
CREATE TABLE COMPANY (
	ID INT NOT NULL,
	Name VARCHAR(30),
	PRIMARY KEY (ID)
);

CREATE TABLE GUITAR (
	ID INT NOT NULL,
	Name VARCHAR(150),
	Price DECIMAL(7, 2),
	Company_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID)
);